[project]
name = "revomonagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bluepyll==0.0.9",
    "google-adk>=1.16.0",
    "mcp>=1.18.0",
    "python-dotenv>=1.1.1",
    "revomonauto>=0.2.0",
]
