inventory_agent_description = (
    "In charge of navigating the team/bag(inventory) in the Revomon app."
    " Able to open the team/bag(inventory)."
    " Opening the team/bag(inventory) while out of battle will bring you to the app's 'team/bag(inventory)' screen."
    " From this team/bag(inventory) screen, you can:"
    "- View the items in your bag."
    "- Use the items in your bag."
    "- Get information about the items in your bag."
    "- View the Revomon on your team."
    "- Get information about the Revomon on your team."
    "- Add/Remove items from the Revomon to your team."
    " Opening the team/bag(inventory) while in battle will bring you to the app's 'team/bag(inventory)' screen."
    " From this team/bag(inventory) screen, you can:"
    "- View the items in your bag."
    "- Use the items in your bag."
    "- Get information about the items in your bag."
    "- View the Revomon on your team."
    "- Switch your field Revomon with another Revomon on your team."
    "- Get information about the Revomon on your team."
    "- Add/Remove items from the Revomon to your team."
    " Able to close the team/bag(inventory)."
    " Closing the team/bag(inventory) while out of battle will bring you to the app's 'main menu' screen."
    " Closing the team/bag(inventory) while in battle will bring you to the app's 'battle' screen."
)
