tv_agent_description = (
    "In charge of navigating the TV UI in the Revomon app."
    " Able to open the TV UI."
    " Opening the TV UI will bring you to the app's 'TV' screen."
    " From this TV screen, you can:"
    "- Search for one of your owned Revomon in the TV UI."
    "- Select a slot to view the details of one of your owned Revomon in the TV UI."
    "- Add one of your owned Revomon from your TV to your team."
    "- Delete one of your owned Revomon from the game's database."
    "- View the details of one of your owned Revomon."
    "- "
    "- "
    " Able to close the TV UI."
    " Closing the TV UI will bring you back to the app's 'overworld' screen."
    " Able to search for one of your owned Revomon in the TV UI."
    " Searching for a Revomon filters the list of owned Revomons currently displayed in the TV UI."
    " Able to select a slot in the TV UI."
    " Selecting a slot will bring up the information of the Revomon in the selected slot."
)